// <auto-generated />
using System;
using AirportWeatherForecastWorkerService.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AirportWeatherForecastWorkerService.Migrations
{
    [DbContext(typeof(TAFContext))]
    [Migration("20241111003032_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("AirportWeatherForecastWorkerService.Models.TAF", b =>
                {
                    b.Property<int>("AirportCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("IssueTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("RawTAF")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("AirportCode", "IssueTime");

                    b.HasIndex("AirportCode", "IssueTime")
                        .IsUnique();

                    b.ToTable("TAFs");
                });
#pragma warning restore 612, 618
        }
    }
}
